import React, { useMemo } from 'react';
import { FlatList, View } from 'react-native';

import { AppText } from '../common/AppText';

// Committed attribution snapshot generated by `npm run attribution`
// (scripts/license-audit.js --generate-attribution assets/THIRD_PARTY_NOTICES.json).
// CI regenerates the authoritative, full transitive production tree.
const THIRD_PARTY_NOTICES = require('../../../assets/THIRD_PARTY_NOTICES.json');

interface PackageAttribution {
  name: string;
  version?: string;
  license: string;
}

export const LicensesScreen = () => {
  const packages = useMemo<PackageAttribution[]>(
    () => THIRD_PARTY_NOTICES.packages ?? [],
    []
  );

  const renderItem = ({ item }: { item: PackageAttribution }) => (
    <View className="flex-row items-center justify-between border-b border-gray-200 px-4 py-3 dark:border-gray-700">
      <View className="flex-1 pr-3">
        <AppText className="text-sm font-medium text-gray-900 dark:text-white">
          {item.name}
        </AppText>
        {item.version ? (
          <AppText className="text-xs text-gray-500 dark:text-gray-400">
            v{item.version}
          </AppText>
        ) : null}
      </View>
      <View className="ml-auto">
        <AppText className="text-xs text-gray-500 dark:text-gray-400">
          {item.license}
        </AppText>
      </View>
    </View>
  );

  return (
    <View className="flex-1 bg-gray-50 dark:bg-gray-900">
      <View className="px-4 pb-2 pt-6">
        <AppText className="text-xl font-bold text-gray-900 dark:text-white">
          Open Source Licenses
        </AppText>
        <AppText className="mt-1 text-xs text-gray-500 dark:text-gray-400">
          This app is built on {packages.length} open-source packages. Licensing
          is enforced in CI by an allowlist; see license-allowlist.json for the
          accepted licenses and license-exceptions.json for approved exceptions.
        </AppText>
      </View>
      <FlatList
        data={packages}
        keyExtractor={(item, index) => `${item.name}-${index}`}
        renderItem={renderItem}
        contentContainerStyle={{ paddingBottom: 32 }}
        ListEmptyComponent={
          <AppText className="px-4 py-6 text-sm text-gray-500 dark:text-gray-400">
            No attribution data available.
          </AppText>
        }
      />
    </View>
  );
};
